name: osrsdata-api-stack

services:
  osrsdata.api:
    container_name: osrsdata-api
    image: osrsdata.api
    build:
      context: .
      dockerfile: OSRSData.Api/Dockerfile
    restart: unless-stopped
    environment:
      # These variables will be pulled from your .env file
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
    ports:
      - "127.0.0.1:5010:8080" # Exposed only to localhost
