name: osrsdata-api-stack

services:
  # --- API ---
  osrsdata.api:
    container_name: osrsdata-api
    image: osrsdata.api
    build:
      context: .
      dockerfile: OSRSData.Api/Dockerfile
    restart: unless-stopped
    depends_on: # This will likely need removed for a true deployment, as the db will likely be on a different host.
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=OSRSData;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "127.0.0.1:5010:8080" # Exposed only to localhost

  # --- Database ---
  db:
    container_name: osrsdata-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=OSRSData
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

